### PR TITLE
Prevent UI freeze caused by intensive prompts

### LINKED ISSUE #1324: UI Freeze Upon Pasting Prompt
**Describe the bug**
Easy-Diffusion UI Freezes when this text is pasted into the prompt field:
"hyperrealistic full length portrait of gorgeous goddess | standing in field full of flowers | detailed gorgeous face!! | full body!! | skimpy armor | god rays | intricate | elegant | realistic | hyperrealistic | cinematic | character design | concept art | highly detailed | illustration | digital art | digital painting | depth of field"

Pasting part of the prompt and manually typing the rest also results in a freeze. I suspect the "|" has something to do with it.

**To Reproduce**
Paste the above prompt into the prompt field

**Expected behavior**
No immediate effects

**Desktop (please complete the following information):**
 - OS: KDE Neon (5.19.0-43-generic)
 - Browser: Librewolf
 - Version: Firefox 113.0.2-1

**Recording**
https://github.com/cmdr2/stable-diffusion-ui/assets/48196283/a0e7cc34-a018-4d1d-98c5-2255767cdaed

### PR DESCRIPTION
**Pull request by ManInDark**
Re-implemented multiple functions in a way that mimics their original function but only returns how many images would be generated from given prompts. The functions are all named after their original with -Number added at the end.

This fixes #1324 

Although I tried to re-implement all necessary function, but some (like applySetOperator) need to run for it to work.

While doing that, I added some comments, but feel free to remove them as they're specific to this fix, and I left them in to sort of show how / what I did.

### CODE REVIEW

**Comment by ManInDark** [comment]
PS: I compared the performance and with this pattern: `1|2|3|4|5|...|n` before it would start to take quite long around n=20 and with this fix it doesn't even sweat at n=30.

PPS: this does not fix the lag if you actually went and sent all the prompts to generate

**Comment by ManInDark** [comment]
Changed all links to now reference easydiffusion/easydiffusion, which closes #1339

File: ui/media/js/main.js [hunk 1]
```diff
@@ -1546,15 +1617,21 @@ heightField.addEventListener("change", onDimensionChange)
...
-        Math.max(parseInt(numOutputsTotalField.value), parseInt(numOutputsParallelField.value)) * getPrompts().length
+        Math.max(parseInt(numOutputsTotalField.value), parseInt(numOutputsParallelField.value)) * getPromptsNumber()
     let imageLabel = "Image"
     if (totalImages > 1) {
         imageLabel = totalImages + " Images"
     }
     if (SD.activeTasks.size == 0) {
-        makeImageBtn.innerText = "Make " + imageLabel
+        if (totalImages >= 10000)
+            makeImageBtn.innerText = "Make tens of thousands of images"
```
Comment (cmdr2) [inline ui/media/js/main.js:1627]: How about "Make 10000+ images", to prevent the button from becoming too long (especially on mobile, which many users use)? Thanks

File: ui/media/js/main.js [hunk 2]
```diff
@@ -1378,6 +1445,10 @@ function permutePrompts(promptBase, promptMatrix) {
     return prompts
 }
 
+function permutePromptsNumber(promptMatrix) { // this should calculate how many different prompts can be made with the prompt matrix
```
Comment (cmdr2) [inline ui/media/js/main.js:1448]: Is this function necessary? How about just calling `permuteNumber(promptMatrix)` in line 1419 directly?

**Comment by cmdr2** [comment]
It's okay if some combinations didn't work in the past. For e.g. I don't know if "matrixes in sets" even work today. In that case, it's okay to ignore that scenario.

Just ensuring that we don't have any regressions (runtime errors, incorrect numbers etc). If a scenario didn't work in the past, then we can ignore that for now. Thanks!

File: ui/media/js/main.js (hunk 2 above)
Comment (ManInDark) [reply ui/media/js/main.js]: Wanted to keep the structure sort of the same to make it easier to follow, but applied suggestion in latest commit.

**Comment by ManInDark** [comment]
Tests:
`1|2|3|4 -> 8`
`1, 2, 3, 4 | {5,6} | 7 -> 8`
`{{1,2},{3,4}} -> 4`

All returned the same length with the new function as with the old one.

Not working was `{1|2|3,4}, 5`, which returned 5 instead of 9, but that didn't appear to work correctly as you mentioned (following what getPrompts() returned when called in the console): `['{1', '1, 5', '3, 5', '4, 5', '{1, 2', '1, 5', '2, 5', '3, 5', '4, 5']`

I applied both of your suggestions in the last commit.

**Comment by ManInDark** [comment]
Just for reference, if someone wants to change the 10k+ display later, I don't think you'd have to keep that feature. This is because the pure number calculation is quite quick and only takes longer the more sets there are, but the time it takes just grows linearly instead of exponentially.

**Comment by cmdr2** [comment]
Thanks @ManInDark ! Sorry for the delay, I was away for a few days. Will review this and merge soon!

**Comment by cmdr2** [comment]
Thanks, and sorry for the long delay! Very nice work :)

**Comment by ManInDark** [comment]
If the testing prompts are used again later:
`{1}` should be tested too, as it caused a problem this time
